name: Run Tests on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-backend:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Verify package-lock.json exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json not found!";
            exit 1;
          fi

      - name: Install Dependencies
        run: npm ci

      - name: Build the Project
        run: npm run build

      - name: Run Tests with Coverage
        run: |
          mkdir -p ./test-results
          npm test -- --ci --coverage --outputFile=./test-results/test-report.xml
        env:
          CI: true

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: ./test-results/test-report.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: ./coverage
